project:
  type: website
  output-dir: _site

date: today

website:
  title: "Real World Evidence Summer School"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  repo-url: https://github.com/oxford-pharmacoepi/RealWordlEvidenceSummerSchool2025
  repo-actions: [issue]
  page-footer:
    center: "Rendered on {{< meta date >}}"
    left: "Copyright 2025, Oxinfer"
    right:
      - text: W
        href: https://oxford-pharmacoepi.github.io/Oxinfer/
      - href: https://github.com/oxford-pharmacoepi
        icon: github
      - href: https://www.youtube.com/@oxinfer
        icon: youtube
  navbar:
    left:
      - text: Program
        href: program.qmd
      - text: Setup
        href: setup.qmd
      - text: Presentations
        href: Presentations/index.qmd
      - text: Practical
        href: practical.qmd
    right:
      - text: W
        href: https://oxford-pharmacoepi.github.io/Oxinfer/
      - href: https://github.com/oxford-pharmacoepi
        icon: github
      - href: https://www.youtube.com/@oxinfer
        icon: youtube

format:
  html:
    toc: true
    theme: cosmo
    search: false
