---
title: "Welcome to the Analytics track"
subtitle: "Real World Evidence Summer School 2025"
format:
  revealjs: 
    theme: [simple, ../styleSS25.scss]
    incremental: true   
    slide-number: true
    chalkboard: true
    preview-links: auto
    margin: 0.07
    code-link: true
    code-line-numbers: false
    height: 900
    width: 1600
    footer: |
      <div style="position: relative; width: 100%;">
        <div style="text-align: center; font-weight: 500;">Real World Evidence Summer School 2025</div>
        <div style="position: absolute; right: 20px; top: -800px;"><a href="index.qmd" style="text-decoration: none;">⬅ Back to Practicals</a></div>
      </div>
execute:
  echo: true
  eval: true
editor: visual
---

## Welcome

<https://oxford-pharmacoepi.github.io/RealWorldEvidenceSummerSchool2025/>

## The OMOP CDM

## The packages

## What to expect

## Goals

## Schedule - Monday

| Time | Session |
| --- | ------ |
| 13:30-14:00 | Welcome and Set up |
| 14:00-14:45 | Introduction to OMOP and **CDMConnector** |
| *14:45-14:55* | *Break* |
| 14:55-15:25 | Character a database using **OmopSketch** |
| *15:25-15:35* | *Break* |
| 15:35-15:45 | General practical introduction |
| 15:45-16:30 | General practical |

## Schedule - Tuesday

| Time | Session |
| --- | ------ |
| 13:30-14:10 | Create codelist using **CodelistGenerator** |
| *14:10-14:20* | *Break* |
| 14:20-15:05 | Create cohorts using **CohortConstructor** |
| *15:05-15:15* | *Break* |
| 15:15-15:45 | Review codelists and cohorts using **PhenotypeR** |
| 15:45-16:30 | General practical |

## Schedule - Wednesday

| Time | Session |
| --- | ------ |
| 13:30-14:20 | Characterise cohorts using **CohortCharacteristics** |
| *14:20-14:30* | *Break* |
| 14:30-15:20 | Estimate Incidence and Prevalence using **IncidencePrevalence** |
| *15:20-15:30* | *Break* |
| 15:30-16:30 | General practical |

## Schedule - Thursday

| Time | Session |
| --- | ------ |
| 13:30-14:20 | Conducting Drug Utilisation studies with **DrugUtilisation** |
| *14:20-14:30* | *Break* |
| 14:30-15:00 | Estimate Survival **CohortSurvival** |
| *15:00-15:10* | *Break* |
| 15:30-16:30 | General practical |

## Set up

Please download the following project: [download project](https://github.com/oxford-pharmacoepi/AnalyticsTrack2025/archive/refs/heads/main.zip)

or if you know about GitHub you can fork the repository: <https://github.com/oxford-pharmacoepi/AnalyticsTrack2025>
