on:
  workflow_dispatch: null
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: rstudio/shiny-workflows/setup-r-package@v1
        with:
          packages: |
            renv
            sessioninfo

      - name: Find package dependencies
        shell: Rscript {0}
        id: packages
        run: |
          # Find package dependencies using {renv} and install with {pak}
          pak::pak(
            unique(renv::dependencies(".")$Package)
          )

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render quarto website
        run: quarto render

      - name: Publish
        if: github.event_name != 'pull_request'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
          publish_dir: ./_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
